### ISSUE TITLE
module 'crypto-js' does not exist in the haste module map

### ISSUE THREAD

**Issue by xiaoosnggao** [quenice/react-native-cacheimage#1]
看样子应该是少装了一个 ‘crypto-js’

![image](https://user-images.githubusercontent.com/16183057/48969440-8c277b80-f039-11e8-8cfe-6e52ada158b4.png)

**Comment by quenice** [comment]
@gaoxiaosong1113 忘了加 `dependencies` 到 `package.json` 中了，谢谢提醒。目前先直接在你项目的 `package.json` 的 `dependencies` 中先加入 `"crypto-js": "^3.1.9-1",` 依赖就可。

**Comment by xiaoosnggao** [comment]
@quenice  好的，我这边已经加了
