### ISSUE TITLE
uri 是不是只支持https的？  http的显示Error: unsupported URL

### ISSUE THREAD

**Issue by xiaoosnggao** [quenice/react-native-cacheimage#2]
![image](https://user-images.githubusercontent.com/16183057/49670216-e1827480-fa9e-11e8-91ce-f2d52c1bf4fc.png)

**Comment by quenice** [comment]
@gaoxiaosong1113 不是我这个插件的限制，这个是RN/android/ios默认支持https，如果需要http，可以做设置。

**Comment by quenice** [comment]
@gaoxiaosong1113 你可以打印出你的url，发这里我看下，看下是否能够帮到你。
